import type { ShipId } from './types';

export interface ShipDef {
  id: ShipId;
  name: string;
  tagline: string;
  color: string;
  accent: string;
  /** Collision radius in arena units */
  radius: number;
  /** Visual / model scale */
  scale: number;
  maxHp: number;
  maxEnergy: number;
  energyRegen: number;
  /** Engine force (accel = thrust / mass) */
  thrust: number;
  /** Max turn rate (rad/s) once spun up */
  turnRate: number;
  /** How fast omega reaches turnRate */
  turnAccel: number;
  /** Angular damping when not steering (0-1 per frame @60hz feel) */
  turnDamp: number;
  mass: number;
  /** Max speed multiplier (base MAX_SPEED / mass * this) */
  speedBias: number;
  fireCost: number;
  fireRate: number;
  specialCost: number;
  specialCooldown: number;
  specialName: string;
  specialDesc: string;
  hull: { x: number; y: number }[];
}

export const SHIPS: Record<ShipId, ShipDef> = {
  solhammer: {
    id: 'solhammer',
    name: 'Boss Brick',
    tagline: 'A flying filing cabinet that packs a nuke.',
    color: '#4cc9ff',
    accent: '#ffe566',
    radius: 20,
    scale: 1.35,
    maxHp: 140,
    maxEnergy: 100,
    energyRegen: 12,
    thrust: 420,
    turnRate: 1.55,
    turnAccel: 3.2,
    turnDamp: 0.92,
    mass: 2.6,
    speedBias: 1.15,
    fireCost: 8,
    fireRate: 0.28,
    specialCost: 55,
    specialCooldown: 4.5,
    specialName: 'Big Red Button',
    specialDesc: 'Yeet a slow seeking boom. Very loud. Very rude.',
    hull: [
      { x: 22, y: 0 },
      { x: 8, y: 10 },
      { x: -16, y: 12 },
      { x: -12, y: 0 },
      { x: -16, y: -12 },
      { x: 8, y: -10 },
    ],
  },
  zephyr: {
    id: 'zephyr',
    name: 'Zippy',
    tagline: 'Caffeine with fins. Blinks when scared.',
    color: '#00ffa8',
    accent: '#e8fff6',
    radius: 10,
    scale: 0.72,
    maxHp: 48,
    maxEnergy: 90,
    energyRegen: 20,
    thrust: 380,
    turnRate: 7.8,
    turnAccel: 32,
    turnDamp: 0.78,
    mass: 0.42,
    speedBias: 1.35,
    fireCost: 5,
    fireRate: 0.16,
    specialCost: 28,
    specialCooldown: 1.6,
    specialName: 'Nope Blink',
    specialDesc: 'Teleport slightly forward. Pretend you meant to.',
    hull: [
      { x: 14, y: 0 },
      { x: 0, y: 5 },
      { x: -10, y: 3 },
      { x: -5, y: 0 },
      { x: -10, y: -3 },
      { x: 0, y: -5 },
    ],
  },
  bulwark: {
    id: 'bulwark',
    name: 'Fort Knob',
    tagline: 'Turns like a fridge. Hits like one falling downstairs.',
    color: '#ffb703',
    accent: '#fff3b0',
    radius: 22,
    scale: 1.5,
    maxHp: 180,
    maxEnergy: 110,
    energyRegen: 10,
    thrust: 380,
    turnRate: 1.25,
    turnAccel: 2.4,
    turnDamp: 0.94,
    mass: 3.2,
    speedBias: 0.95,
    fireCost: 10,
    fireRate: 0.38,
    specialCost: 35,
    specialCooldown: 3.2,
    specialName: 'Nope Shield',
    specialDesc: 'Pop a shiny bubble. Bullets bounce. Ego inflates.',
    hull: [
      { x: 16, y: 0 },
      { x: 10, y: 14 },
      { x: -14, y: 16 },
      { x: -18, y: 0 },
      { x: -14, y: -16 },
      { x: 10, y: -14 },
    ],
  },
  shade: {
    id: 'shade',
    name: 'Sneaky Pete',
    tagline: 'Now you see him. Now you are dead. Now he left.',
    color: '#b24bf3',
    accent: '#f5e1ff',
    radius: 12,
    scale: 0.85,
    maxHp: 65,
    maxEnergy: 100,
    energyRegen: 16,
    thrust: 340,
    turnRate: 5.6,
    turnAccel: 20,
    turnDamp: 0.8,
    mass: 0.7,
    speedBias: 1.2,
    fireCost: 6,
    fireRate: 0.12,
    specialCost: 20,
    specialCooldown: 0.5,
    specialName: 'Invisible Mode',
    specialDesc: 'Cloak up, stab once, ghost out like a coward legend.',
    hull: [
      { x: 14, y: 0 },
      { x: 2, y: 7 },
      { x: -14, y: 5 },
      { x: -8, y: 0 },
      { x: -14, y: -5 },
      { x: 2, y: -7 },
    ],
  },
  prism: {
    id: 'prism',
    name: 'Disco Ball',
    tagline: 'Throws shiny rocks. Starts parties. Ends friendships.',
    color: '#5ce1ff',
    accent: '#f0fbff',
    radius: 14,
    scale: 1.0,
    maxHp: 85,
    maxEnergy: 120,
    energyRegen: 20,
    thrust: 320,
    turnRate: 3.9,
    turnAccel: 14,
    turnDamp: 0.84,
    mass: 1.05,
    speedBias: 1.1,
    fireCost: 7,
    fireRate: 0.22,
    specialCost: 45,
    specialCooldown: 3.8,
    specialName: 'Confetti Bomb',
    specialDesc: 'Shatter nova. Sparkly. Mean.',
    hull: [
      { x: 16, y: 0 },
      { x: 4, y: 10 },
      { x: -10, y: 8 },
      { x: -4, y: 0 },
      { x: -10, y: -8 },
      { x: 4, y: -10 },
    ],
  },
  brood: {
    id: 'brood',
    name: 'Bug Bus',
    tagline: 'Rent is due and the tenants bite.',
    color: '#39ff14',
    accent: '#d8ffe0',
    radius: 17,
    scale: 1.25,
    maxHp: 105,
    maxEnergy: 100,
    energyRegen: 12,
    thrust: 360,
    turnRate: 2.1,
    turnAccel: 5.5,
    turnDamp: 0.9,
    mass: 2.0,
    speedBias: 1.0,
    fireCost: 9,
    fireRate: 0.4,
    specialCost: 40,
    specialCooldown: 5.0,
    specialName: 'Release the Roommates',
    specialDesc: 'Spawn hungry drones. They do not share snacks.',
    hull: [
      { x: 12, y: 0 },
      { x: 8, y: 10 },
      { x: -6, y: 12 },
      { x: -14, y: 4 },
      { x: -14, y: -4 },
      { x: -6, y: -12 },
      { x: 8, y: -10 },
    ],
  },
  cinder: {
    id: 'cinder',
    name: 'Hot Mess',
    tagline: 'Leaves a trail of bad decisions on fire.',
    color: '#ff2e63',
    accent: '#ffd6e0',
    radius: 12,
    scale: 0.88,
    maxHp: 70,
    maxEnergy: 95,
    energyRegen: 15,
    thrust: 400,
    turnRate: 5.2,
    turnAccel: 22,
    turnDamp: 0.8,
    mass: 0.62,
    speedBias: 1.28,
    fireCost: 4,
    fireRate: 0.1,
    specialCost: 8,
    specialCooldown: 0.15,
    specialName: 'Floor Is Lava',
    specialDesc: 'Burn a wake behind you. Smell the drama.',
    hull: [
      { x: 18, y: 0 },
      { x: 0, y: 8 },
      { x: -16, y: 6 },
      { x: -10, y: 0 },
      { x: -16, y: -6 },
      { x: 0, y: -8 },
    ],
  },
  grappler: {
    id: 'grappler',
    name: 'Grabby',
    tagline: 'Personal space? Never heard of her.',
    color: '#ff77e9',
    accent: '#ffe0f7',
    radius: 15,
    scale: 1.1,
    maxHp: 100,
    maxEnergy: 110,
    energyRegen: 14,
    thrust: 300,
    turnRate: 3.2,
    turnAccel: 10,
    turnDamp: 0.86,
    mass: 1.35,
    speedBias: 1.05,
    fireCost: 12,
    fireRate: 0.5,
    specialCost: 6,
    specialCooldown: 0.1,
    specialName: 'Yoink Beam',
    specialDesc: 'Tractor hug. Limpet kisses. Awkward for everyone.',
    hull: [
      { x: 10, y: 0 },
      { x: 14, y: 8 },
      { x: -8, y: 12 },
      { x: -16, y: 0 },
      { x: -8, y: -12 },
      { x: 14, y: -8 },
    ],
  },
  scuttle: {
    id: 'scuttle',
    name: 'Chicken',
    tagline: 'Runs away professionally. Wins anyway.',
    color: '#ffe566',
    accent: '#fff8c8',
    radius: 11,
    scale: 0.78,
    maxHp: 58,
    maxEnergy: 100,
    energyRegen: 18,
    thrust: 360,
    turnRate: 6.5,
    turnAccel: 26,
    turnDamp: 0.76,
    mass: 0.5,
    speedBias: 1.32,
    fireCost: 5,
    fireRate: 0.2,
    specialCost: 18,
    specialCooldown: 1.2,
    specialName: 'Scream Boost',
    specialDesc: 'Panic thrusters plus a rear missile of spite.',
    hull: [
      { x: 12, y: 0 },
      { x: 4, y: 9 },
      { x: -10, y: 7 },
      { x: -16, y: 0 },
      { x: -10, y: -7 },
      { x: 4, y: -9 },
    ],
  },
  nullpoint: {
    id: 'nullpoint',
    name: 'Void Weirdo',
    tagline: 'Drinks your battery like a juice box.',
    color: '#7c83ff',
    accent: '#e8ecff',
    radius: 14,
    scale: 1.05,
    maxHp: 90,
    maxEnergy: 130,
    energyRegen: 10,
    thrust: 280,
    turnRate: 3.5,
    turnAccel: 9,
    turnDamp: 0.88,
    mass: 1.15,
    speedBias: 1.08,
    fireCost: 0,
    fireRate: 0.05,
    specialCost: 40,
    specialCooldown: 4.0,
    specialName: 'Ghost Sip',
    specialDesc: 'Drain cone, then phase somewhere less stabbed.',
    hull: [
      { x: 15, y: 0 },
      { x: 6, y: 9 },
      { x: -12, y: 7 },
      { x: -6, y: 0 },
      { x: -12, y: -7 },
      { x: 6, y: -9 },
    ],
  },
  stormlance: {
    id: 'stormlance',
    name: 'Sparky',
    tagline: 'Forks lightning. Also forks your afternoon.',
    color: '#c77dff',
    accent: '#f3e8ff',
    radius: 13,
    scale: 0.92,
    maxHp: 68,
    maxEnergy: 115,
    energyRegen: 17,
    thrust: 350,
    turnRate: 4.4,
    turnAccel: 16,
    turnDamp: 0.82,
    mass: 0.75,
    speedBias: 1.18,
    fireCost: 6,
    fireRate: 0.18,
    specialCost: 38,
    specialCooldown: 3.4,
    specialName: 'Chain Tantrum',
    specialDesc: 'Arc bolts that hop ship to ship like gossip.',
    hull: [
      { x: 16, y: 0 },
      { x: 4, y: 6 },
      { x: -12, y: 4 },
      { x: -8, y: 0 },
      { x: -12, y: -4 },
      { x: 4, y: -6 },
    ],
  },
  mirage: {
    id: 'mirage',
    name: 'Fakeout',
    tagline: 'Was here. Was not. Your shot is embarrassed.',
    color: '#e0aaff',
    accent: '#faf0ff',
    radius: 12,
    scale: 0.86,
    maxHp: 56,
    maxEnergy: 105,
    energyRegen: 16,
    thrust: 340,
    turnRate: 5.2,
    turnAccel: 20,
    turnDamp: 0.78,
    mass: 0.52,
    speedBias: 1.26,
    fireCost: 5,
    fireRate: 0.14,
    specialCost: 22,
    specialCooldown: 1.85,
    specialName: 'Swap Places',
    specialDesc: 'Mirror step through their shot. Petty excellence.',
    hull: [
      { x: 14, y: 0 },
      { x: 2, y: 8 },
      { x: -12, y: 5 },
      { x: -6, y: 0 },
      { x: -12, y: -5 },
      { x: 2, y: -8 },
    ],
  },
  harrier: {
    id: 'harrier',
    name: 'Divebomb Dave',
    tagline: 'Gravity is a lifestyle brand.',
    color: '#ff9f1c',
    accent: '#ffe5c4',
    radius: 14,
    scale: 1.05,
    maxHp: 88,
    maxEnergy: 100,
    energyRegen: 13,
    thrust: 360,
    turnRate: 3.4,
    turnAccel: 11,
    turnDamp: 0.85,
    mass: 1.2,
    speedBias: 1.12,
    fireCost: 8,
    fireRate: 0.28,
    specialCost: 32,
    specialCooldown: 2.8,
    specialName: 'Kamikaze Lite',
    specialDesc: 'Screaming dive. Release bombs. Climb like you planned it.',
    hull: [
      { x: 16, y: 0 },
      { x: 6, y: 10 },
      { x: -10, y: 8 },
      { x: -14, y: 0 },
      { x: -10, y: -8 },
      { x: 6, y: -10 },
    ],
  },
  minewright: {
    id: 'minewright',
    name: 'Litterbug',
    tagline: 'Decorates space with regret.',
    color: '#8d99ae',
    accent: '#eef2f7',
    radius: 16,
    scale: 1.15,
    maxHp: 110,
    maxEnergy: 100,
    energyRegen: 12,
    thrust: 300,
    turnRate: 2.4,
    turnAccel: 6.5,
    turnDamp: 0.9,
    mass: 1.8,
    speedBias: 0.98,
    fireCost: 10,
    fireRate: 0.45,
    specialCost: 42,
    specialCooldown: 4.5,
    specialName: 'Party Poppers',
    specialDesc: 'Drop a mine ring. Force them through the bad vibes.',
    hull: [
      { x: 12, y: 0 },
      { x: 8, y: 12 },
      { x: -10, y: 12 },
      { x: -16, y: 0 },
      { x: -10, y: -12 },
      { x: 8, y: -12 },
    ],
  },
  razorwing: {
    id: 'razorwing',
    name: 'Blender',
    tagline: 'Close-range haircut specialist.',
    color: '#ff4d6d',
    accent: '#ffd6e7',
    radius: 12,
    scale: 0.9,
    maxHp: 70,
    maxEnergy: 100,
    energyRegen: 15,
    thrust: 370,
    turnRate: 5.4,
    turnAccel: 20,
    turnDamp: 0.78,
    mass: 0.65,
    speedBias: 1.25,
    fireCost: 7,
    fireRate: 0.32,
    specialCost: 36,
    specialCooldown: 3.0,
    specialName: 'Face Fan',
    specialDesc: 'Shotgun needles, then a blade fan to the nose.',
    hull: [
      { x: 15, y: 0 },
      { x: 0, y: 9 },
      { x: -12, y: 4 },
      { x: -6, y: 0 },
      { x: -12, y: -4 },
      { x: 0, y: -9 },
    ],
  },
  glacier: {
    id: 'glacier',
    name: 'Ice Cube',
    tagline: 'Slow. Mean. Unexpectedly cold-blooded.',
    color: '#48cae4',
    accent: '#e0fbff',
    radius: 18,
    scale: 1.28,
    maxHp: 130,
    maxEnergy: 105,
    energyRegen: 11,
    thrust: 340,
    turnRate: 1.7,
    turnAccel: 3.8,
    turnDamp: 0.93,
    mass: 2.5,
    speedBias: 0.96,
    fireCost: 9,
    fireRate: 0.36,
    specialCost: 40,
    specialCooldown: 3.6,
    specialName: 'Chill Out',
    specialDesc: 'Freeze pulse. Then walk them down like a glacier with beef.',
    hull: [
      { x: 14, y: 0 },
      { x: 8, y: 14 },
      { x: -12, y: 14 },
      { x: -18, y: 0 },
      { x: -12, y: -14 },
      { x: 8, y: -14 },
    ],
  },
  swarmlord: {
    id: 'swarmlord',
    name: 'Bee Movie',
    tagline: 'The bees are not unionized.',
    color: '#b0f2c2',
    accent: '#f1ffe8',
    radius: 15,
    scale: 1.12,
    maxHp: 88,
    maxEnergy: 120,
    energyRegen: 14,
    thrust: 335,
    turnRate: 3.0,
    turnAccel: 9,
    turnDamp: 0.86,
    mass: 1.35,
    speedBias: 1.08,
    fireCost: 5,
    fireRate: 0.18,
    specialCost: 40,
    specialCooldown: 4.6,
    specialName: 'Angry Cloud',
    specialDesc: 'Locust cloud. More bees. Worse bees.',
    hull: [
      { x: 13, y: 0 },
      { x: 6, y: 10 },
      { x: -8, y: 11 },
      { x: -14, y: 3 },
      { x: -14, y: -3 },
      { x: -8, y: -11 },
      { x: 6, y: -10 },
    ],
  },
  pulsejet: {
    id: 'pulsejet',
    name: 'Thumper',
    tagline: 'Punches first. Asks never.',
    color: '#ff6b6b',
    accent: '#ffe3e3',
    radius: 14,
    scale: 1.0,
    maxHp: 92,
    maxEnergy: 110,
    energyRegen: 14,
    thrust: 340,
    turnRate: 3.6,
    turnAccel: 12,
    turnDamp: 0.84,
    mass: 1.1,
    speedBias: 1.1,
    fireCost: 7,
    fireRate: 0.2,
    specialCost: 34,
    specialCooldown: 2.6,
    specialName: 'Whoosh Slap',
    specialDesc: 'Shockwave at hugging range. Reset the scramble.',
    hull: [
      { x: 15, y: 0 },
      { x: 4, y: 9 },
      { x: -11, y: 7 },
      { x: -7, y: 0 },
      { x: -11, y: -7 },
      { x: 4, y: -9 },
    ],
  },
  railfox: {
    id: 'railfox',
    name: 'Laser Pointer',
    tagline: 'One shot. Many feelings.',
    color: '#ffd60a',
    accent: '#fff3bf',
    radius: 13,
    scale: 0.95,
    maxHp: 75,
    maxEnergy: 120,
    energyRegen: 14,
    thrust: 310,
    turnRate: 3.8,
    turnAccel: 13,
    turnDamp: 0.83,
    mass: 0.95,
    speedBias: 1.08,
    fireCost: 8,
    fireRate: 0.3,
    specialCost: 48,
    specialCooldown: 4.0,
    specialName: 'Red Dot of Doom',
    specialDesc: "Piercing rail. Hold angle. Ruin someone's day.",
    hull: [
      { x: 18, y: 0 },
      { x: 2, y: 5 },
      { x: -14, y: 4 },
      { x: -10, y: 0 },
      { x: -14, y: -4 },
      { x: 2, y: -5 },
    ],
  },
  sanguine: {
    id: 'sanguine',
    name: 'Mosquito',
    tagline: 'Heals by being extremely rude.',
    color: '#ff1744',
    accent: '#ffd5d5',
    radius: 13,
    scale: 0.98,
    maxHp: 80,
    maxEnergy: 115,
    energyRegen: 12,
    thrust: 325,
    turnRate: 4.0,
    turnAccel: 14,
    turnDamp: 0.82,
    mass: 0.9,
    speedBias: 1.14,
    fireCost: 7,
    fireRate: 0.24,
    specialCost: 36,
    specialCooldown: 3.2,
    specialName: 'Blood Juice Box',
    specialDesc: 'Siphon at point blank. Gross. Effective.',
    hull: [
      { x: 14, y: 0 },
      { x: 4, y: 8 },
      { x: -10, y: 6 },
      { x: -14, y: 0 },
      { x: -10, y: -6 },
      { x: 4, y: -8 },
    ],
  },
};

export const SHIP_LIST: ShipDef[] = Object.values(SHIPS);
